- name: creating a user with name Roboshop
  hosts: localhost
  tasks:
    # when you dont find required module, you can use ansible.builtin.command to use linux commands directly
    # when user does not exist, ansible treat that as failure and come out by default
    # to avoid that we can use ignore failures
    - name: checking if roboshop user already exist
      ansible.builtin.command: id roboshop
      register: output #previous command result is stored under variable to output
      ignore_errors: true

    - name: print the result
      ansible.builtin.debug:
        msg: "Output is {{output}}"

    - name: printing the exit status
      ansible.builtin.debug:
        msg: "exitstatus is {{output.rc}}"

    - name: creating user if already not exist
      become: yes
      ansible.builtin.user:
        name: roboshop
      when: output.rc !=0 #if this statement is true, then only this module execute
