- name: loops in ansible
  hosts: localhost
  tasks:
    - name: install packages from list
      ansible.builtin.yum:
        name: { { item } }
        state: installed
      loop:
        - mysql
        - postfix
        - mailx
        - nginx
