- name: loops in ansible
  hosts: localhost
  tasks:
    - name: print the names from list
      ansible.builtin.debug:
        msg: "Hello {{item}}"
      loop:
        - subba
        - reddy
        - dadi
        - reddy
