- name: loops in ansible
  hosts: localhost
  become: yes
  tasks:
    - name: install packages from list
      ansible.builtin.yum:
        name: "{{ item.name }}"
        state: "{{item.state}}"
      loop:
        - { name: "mysql", state: "absent" }
        - { name: "postfix", state: "installed" }
        - { name: "mailx", state: "absent" }
        - { name: "cyrus-sasl-plain", state: "installed" }
