---
- name: installing a package in node1
  hosts: all
  become: yes
  become_user: root

  tasks:
    - name: Enable amazon-linux-extras packages
      shell: amazon-linux-extras enable postgresql14

    - name: uninstall nginx in node1
      shell: amazon-linux-extras remove nginx1 -y

    - name: stopping nginx server
      ansible.builtin.service:
        enabled: yes
        name: nginx
        state: stopped
