---
- name: installing a package in node1
  hosts: all
  become: yes
  become_user: root

  tasks:
    - command: amazon-linux-extras install nginx-1.26.0=latest -y
      args:
        creates: /sbin/nginx

    - name: install nginx in node1
      yum:
        name: nginx1
        state: latest
    - name: starting nginx server
      ansible.builtin.service:
        enabled: yes
        name: nginx1
        state: started
