---
- name: installing a package in node1
  hosts: all
  become: yes
  become_user: root

  tasks:
    - name: Enable amazon-linux-extras packages
      shell: amazon-linux-extras enable postgresql14

    - name: uninstall nginx in node1
      ansible.builtin.yum:
        name: nginx
        state: absent
