- name: checking the precendence of different variables
  hosts: node1
  # vars:
  #   NAME: Subbareddy-play
  # vars_files:
  #   - variables.yml
  # vars_prompt:
  #   - name: NAME
  #     prompt: please enter your name
  #     private: false
  tasks:
    - name: variable at task level
      #   vars:
      #     NAME: subbareddy-task
      ansible.builtin.debug:
        msg: "name is: {{NAME}}"
#1. arguments
#2. task level
#3. files
#4. prompt
#5. play
#6. inventory
