- name: checking the precendence of different variables
  host: node1
  Vars:
    name: Subbareddy-play
  vars_files:
    - variables.yml
  vars_prompt:
    - name: name
      prompt: please enter your name
      private: false
    - name: name
      vars:
        name: subbareddy-task
  tasks:
    name: printing name
    ansible.builtin.debug:
      msg: "name is: {{name}}"
