- name: checking the precendence of different variables
  hosts: node1
  vars:
    NAME: Subbareddy-play
  vars_files:
    - variables.yml
  vars_prompt:
    - name: name
      prompt: please enter your name
      private: false
    - name: name
      vars:
        NAME: subbareddy-task
  tasks:
    - name: printing name
      ansible.builtin.debug:
        msg: "name is: {{NAME}}"
