- name: Variables from files
  hosts: localhost
  vars_files:
    - variables.yml
  tasks:
    - name: Printing variables
      ansible.builtin.debug:
        msg: "I am learning {{COURSE}} from trainer {{TRAINER}} for duration of {{DURATION}}"
