- name: Creating catalogue app server
  hosts: catalogue
  become: yes
  tasks:
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /app
        state: directory

    - name: install gcc
      ansible.builtin.shell: yum install -y gcc-c++ make

    - name: install repos
      ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_20.x | sudo -E bash -

    - name: install repos
      ansible.builtin.shell: yum install -y nodejs
