- name: Creating catalogue app server
  hosts: catalogue
  become: yes
  tasks:
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /app
        state: directory

    - name: installs nvm (Node Version Manager)
      ansible.builtin.shell: "curl -fsSL https://fnm.vercel.app/install | bash"
      args:
        chdir: /app

    - name: load nvm
      ansible.builtin.shell: "source ~/.bashrc"

    - name: install nodejs
      ansible.builtin.shell: "fnm use --install-if-missing 20"
