- name: Creating catalogue app server
  hosts: catalogue
  become: yes
  tasks:
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /app
        state: directory

    - name: installs nvm (Node Version Manager)
      ansible.builtin.shell: "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash"
      args:
        chdir: /app

    - name: export nvm
      ansible.builtin.command: export NVM_DIR="$HOME/.nvm"

    - name: This loads nvm
      ansible.builtin.command: [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

    - name: This loads nvm bash_completion
      ansible.builtin.command: [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

    - name: install nodejs
      ansible.builtin.shell: "nvm install 20"
