- name: Installing application server with name catalogue
  hosts: node2
  become: yes
  tasks:
    - name: Install EPEL packages
      ansible.builtin.shell: "sudo yum install https://rpm.nodesource.com/pub_20.x/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm"

    - name: Install EPEL packages
      ansible.builtin.shell: "sudo yum install nodejs -y --setopt=nodesource-nodejs.module_hotfixes=1"

    - name: checking if roboshop user already exist
      ansible.builtin.command: id roboshop
      register: output
      ignore_errors: true

    - name: creating user if already not exist
      ansible.builtin.user:
        name: roboshop
      when: output.rc !=0

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download the application code to created app directory
      ansible.builtin.get_url:
        url: curl -o /tmp/catalogue.zip https://roboshop-builds.s3.amazonaws.com/catalogue.zip
        dest: /app

    - name: Unarchive a file that is already on the remote machine
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /tmp/
        remote_src: yes
