- name: Installing application server with name catalogue
  hosts: node2
  become: yes
  tasks:
    - name: curl installation
      ansible.builtin.yum:
        name: curl
        state: installed

    - name: Download the nodejs setup script
      ansible.builtin.get_url:
        url: curl -fsSL https://rpm.nodesource.com/setup_18.x -o nodesource_setup.sh
        dest: /tmp/

    - name: installing nodejs
      ansible.builtin.shell: "bash nodesource_setup.sh"

    - name: checking if roboshop user already exist
      ansible.builtin.command: id roboshop
      register: output
      ignore_errors: true

    - name: creating user if already not exist
      ansible.builtin.user:
        name: roboshop
      when: output.rc !=0

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download the application code to created app directory
      ansible.builtin.get_url:
        url: curl -o /tmp/catalogue.zip https://roboshop-builds.s3.amazonaws.com/catalogue.zip
        dest: /app

    - name: Unarchive a file that is already on the remote machine
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /tmp/
        remote_src: yes
