- name: Installing mongodb
  hosts: node1
  become: yes
  tasks:
    - name: copying the mongodb repos
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/

    - name: installing mongodb
      ansible.builtin.yum:
        name: mongodb-org
        state: installed

    - name: starting and enabling the mongodb
      ansible.builtin.service:
        name: mongod
        state: started
        enabled: yes

    - name: Update listen address from 127.0.0.1 to 0.0.0.0 in /etc/mongod.conf
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: "127.0.0.1"
        replace: "0.0.0.0"

    - name: Restart the service mongodb
      ansible.builtin.service:
        name: mongod
        state: restarted
